### ISSUE TITLE
Config file is missing

### ISSUE THREAD

**Issue by codsec** [HeiseMo/v-rising-discord-bot#2]
the tittle say everyting

**Comment by codsec** [comment]
![image](https://user-images.githubusercontent.com/44205014/171705837-606f906e-c047-4f22-ae51-300aa0573621.png)
help?

**Comment by DoubtfulHermit** [comment]
Hello @codsec thanks for reaching out, unfortunately I just saw your issue. I have fixed the problem and you should be able to get the config file now.

Additionally I have added a small section to the readme file regarding the ENV you will need to put in.

Thanks for trying the bot out and please let me know if you have some ideas! I have a discord for testing new stuff https://discord.gg/tgp5y9vbQS
